<a href="https://www.kaggle.com/code/manishkr1754/kagglex-skill-assessment-challenge?scriptVersionId=185315182" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

---
<center><h1>KaggleX Skill Assessment Challenge</h1></center>
<center><h3>Part of KaggleX Fellowship Program</h3></center>

---

# Process Flow of the Project

1. Understanding Problem Statement
2. Getting System Ready
3. Data Collection
4. Understanding the Data-Data Eyeballing & Data Description
5. Data Cleaning & Preprocessing I
6. Exploratory Data Analysis (EDA)
7. Univariate Analysis
8. Bivariate Analysis
9. Multivariate Analysis
10. Data Cleaning & Preprocessing II
11. Insights from Data Visualization
12. Feature Engineerig
13. Model Buidling & Evaluation
14. Selection of Best Model & Hyperparameter Tuninng
15. Extracting Submission csv file
16. Generating Pickle file
17. Model Deployment on Hugging Face

# 1) Understanding Problem Statement
---

**The KaggleX Skill Assessment Challenge involves using Used Car Price Prediction Dataset.**

#### Problem Statement:

The used car market in India is a dynamic and ever-changing landscape. Prices can fluctuate wildly based on a variety of factors including the make and model of the car, its mileage, its condition and the current market conditions. As a result, it can be difficult for sellers to accurately price their cars.

#### Approach:

We propose to develop a machine learning model that can predict the price of a used car based on its features. The model will be trained on a dataset of used cars that have been sold. The model will then be able to be used to predict the price of any used car, given its features.

#### Objective:

To build suitable Machine Learning Model for Used Car Price Prediction.

#### Benefits:

The benefits of this solution include:

- Sellers will be able to more accurately price their cars which will help them to sell their cars faster and for a higher price.
- Buyers will be able to find cars that are priced more competitively.
- The overall used car market will become more efficient.

**We believe that this project has the potential to make a significant impact on the used car market. We are excited to work on this project and to see the positive impact that it can have.**

# 2) Getting System Ready
---

#### Import Data and Required Packages

Importing Pandas, Numpy, Matplotlib, Seaborn and Warnings Library

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import warnings

warnings.filterwarnings("ignore")

%matplotlib inline

# 3) Data Collection
---

The Data collection step is not required here since data is already available at [KaggleX Challenge Dataset](https://www.kaggle.com/competitions/kagglex-cohort4/data). However, I will perform how to scrap data from Git Hub repo. The same data is available on a GitHub repo. We can directly download the data from the repo and use it to train the model.

#### Download and Import the CSV Data as Pandas DataFrame

In [12]:
# Importing Train Data

import os
from six.moves import urllib
import urllib.request

# Define the download directory
download_dir = "./data/"

# URL of the file to download
download_url = "https://raw.githubusercontent.com/manishkr1754/KaggleX_Skill_Assessment_Challenge/main/data/train.csv"

# Create the download directory if it doesn't exist
os.makedirs(download_dir, exist_ok=True)

# Get the filename from the URL
filename = os.path.basename(download_url)

# Define the full download path
download_file_path = os.path.join(download_dir, filename)

# Download the file
urllib.request.urlretrieve(download_url, download_file_path)

# Print confirmation
print('-' * 100)
print(f'Data with name {filename} downloaded at {download_file_path}')
print('-' * 100)

# Read the CSV file into a DataFrame
train_df = pd.read_csv(download_file_path, index_col=[0]

----------------------------------------------------------------------------------------------------
Data with name train.csv downloaded at ./data/train.csv
----------------------------------------------------------------------------------------------------

In [15]:
# Importing Test Data

import os
from six.moves import urllib
import urllib.request

# Define the download directory
download_dir = "./data/"

# URL of the file to download
download_url = "https://raw.githubusercontent.com/manishkr1754/KaggleX_Skill_Assessment_Challenge/main/data/test.csv"

# Create the download directory if it doesn't exist
os.makedirs(download_dir, exist_ok=True)

# Get the filename from the URL
filename = os.path.basename(download_url)

# Define the full download path
download_file_path = os.path.join(download_dir, filename)

# Download the file
urllib.request.urlretrieve(download_url, download_file_path)

# Print confirmation
print('-' * 100)
print(f'Data with name {filename} downloaded at {download_file_path}')
print('-' * 100)

# Read the CSV file into a DataFrame
test_df = pd.read_csv(download_file_path, index_col=[0])

----------------------------------------------------------------------------------------------------
Data with name test.csv downloaded at ./data/test.csv
----------------------------------------------------------------------------------------------------

# 4) Understanding Data- Data Eyeballing & Data Description
---

In [16]:
train_df.head()

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price
id,,,,,,,,,,,,
0,Ford,F-150 Lariat,2018,74349,Gasoline,375.0HP 3.5L V6 Cylinder Engine Gasoline Fuel,10-Speed A/T,Blue,Gray,None reported,Yes,11000
1,BMW,335 i,2007,80000,Gasoline,300.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,6-Speed M/T,Black,Black,None reported,Yes,8250
2,Jaguar,XF Luxury,2009,91491,Gasoline,300.0HP 4.2L 8 Cylinder Engine Gasoline Fuel,6-Speed A/T,Purple,Beige,None reported,Yes,15000
3,BMW,X7 xDrive40i,2022,2437,Hybrid,335.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,Transmission w/Dual Shift Mode,Gray,Brown,None reported,Yes,63500
4,Pontiac,Firebird Base,2001,111000,Gasoline,200.0HP 3.8L V6 Cylinder Engine Gasoline Fuel,A/T,White,Black,None reported,Yes,7850

In [17]:
print('The size of Dataframe is: ', train_df.shape)
print('-'*100)
print('The Column Name, Record Count and Data Types are as follows: ')
train_df.info()
print('-'*100)

The size of Dataframe is:  (54273, 12)
----------------------------------------------------------------------------------------------------
The Column Name, Record Count and Data Types are as follows:
<class 'pandas.core.frame.DataFrame'>
Index: 54273 entries, 0 to 54272
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   brand         54273 non-null  object
 1   model         54273 non-null  object
 2   model_year    54273 non-null  int64
 3   milage        54273 non-null  int64
 4   fuel_type     54273 non-null  object
 5   engine        54273 non-null  object
 6   transmission  54273 non-null  object
 7   ext_col       54273 non-null  object
 8   int_col       54273 non-null  object
 9   accident      54273 non-null  object
 10  clean_title   54273 non-null  object
 11  price         54273 non-null  int64
dtypes: int64(3), object(9)
memory usage: 5.4+ MB
----------------------------------------------------------------------------------------------------

In [21]:
# Defining numerical & categorical columns

numeric_features = [feature for feature in train_df.columns if train_df[feature].dtype != 'O']
categorical_features = [feature for feature in train_df.columns if train_df[feature].dtype == 'O']

# print columns

print('We have {} numerical features : {}'.format(len(numeric_features), numeric_features))
print('\nWe have {} categorical features : {}'.format(len(categorical_features), categorical_features))

We have 3 numerical features : ['model_year', 'milage', 'price']

We have 9 categorical features : ['brand', 'model', 'fuel_type', 'engine', 'transmission', 'ext_col', 'int_col', 'accident', 'clean_title']

#### Data Description

- **brand:** Brand Name of the particular car.
- **model:** Exact model name of the car of a particular brand.
- **model_year:** Manufacturing year of the vehicle crucial for assessing depreciation and technology advancements.
- **mileage:** It is usually the number of kilometer the car runs per litre. However, seesing the values it can be inferred as total distance travlled by the vehicle in miles. Key indicator of wear and tear potential maintenance requirements.
- **fuel_type:** Fuel used in the used car whether it's gasoline, diesel, electric or hybrid.
- **engine:** Engine specifications shedding light on performance and efficiency
- **transmission:** Transmission used in the used car whether automatic, manual or another variant.
- **ext_col:** Aesthetic aspectic- Exterior color
- **int_col:** Aesthetic aspectic- Interior color
- **accident:** Vehicle history of accidents or damage crucial for informed decision making.
- **clean_title:** It means that vehicle has never been deemed a total loss or experienced any severe damage due to accident, flood, fire etc.
- **price:** The listed sale price of the vehicle to help in price comparison and budgeting

In [25]:
print('Missing Value Presence in different columns of DataFrame are as follows: ')
print('-'*100)

total = train_df.isnull().sum().sort_values(ascending=False)
percent = (train_df.isnull().sum()/train_df.isnull().count()*100).sort_values(ascending=False)
pd.concat([total, percent], axis=1, keys=['Total', 'Percent'])

Missing Value Presence in different columns of DataFrame are as follows:
----------------------------------------------------------------------------------------------------

              Total  Percent
brand             0      0.0
model             0      0.0
model_year        0      0.0
milage            0      0.0
fuel_type         0      0.0
engine            0      0.0
transmission      0      0.0
ext_col           0      0.0
int_col           0      0.0
accident          0      0.0
clean_title       0      0.0
price             0      0.0

#### Inference

After inspecting the train data, **no missing values** found.

In [26]:
print('Summary Statistics of numerical features for DataFrame are as follows:')
print('-'*100)
train_df.describe()

Summary Statistics of numerical features for DataFrame are as follows:
----------------------------------------------------------------------------------------------------

         model_year         milage         price
count  54273.000000   54273.000000  5.427300e+04
mean    2015.091979   72746.175667  3.921844e+04
std        5.588909   50469.490448  7.282634e+04
min     1974.000000     100.000000  2.000000e+03
25%     2012.000000   32268.000000  1.550000e+04
50%     2016.000000   66107.000000  2.800000e+04
75%     2019.000000  102000.000000  4.500000e+04
max     2024.000000  405000.000000  2.954083e+06

In [27]:
print('Summary Statistics of categorical features for DataFrame are as follows:')
print('-'*100)
train_df.describe(include= 'object')

Summary Statistics of categorical features for DataFrame are as follows:
----------------------------------------------------------------------------------------------------

,brand,model,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title
count,54273,54273,54273,54273,54273,54273,54273,54273,54273
unique,53,1827,7,1061,46,260,124,2,1
top,BMW,F-150 XLT,Gasoline,300.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,A/T,Black,Black,None reported,Yes
freq,7369,780,49439,1452,16757,15078,31820,39896,54273

In [29]:
print('-'*125)
print('Checking records for mis-spell, typo-error etc.')
print('-'*125)

print("'brand' variable have {} unique category : \n{}\n".format(train_df['brand'].nunique(), train_df['brand'].unique()))
print('-'*125)

print("'model' variable have {} unique category : \n{}\n".format(train_df['model'].nunique(), train_df['model'].unique()))
print('-'*125)

print("'fuel_type' variable have {} unique category : \n{}\n".format(train_df['fuel_type'].nunique(), train_df['fuel_type'].unique()))
print('-'*125)

print("'engine' variable have {} unique category : \n{}\n".format(train_df['engine'].nunique(), train_df['engine'].unique()))
print('-'*125)

print("'transmission' variable have {} unique category : \n{}\n".format(train_df['transmission'].nunique(), train_df['transmission'].unique()))
print('-'*125)

print("'ext_col' variable have {} unique category : \n{}\n".format(train_df['ext_col'].nunique(), train_df['ext_col'].unique()))
print('-'*125)

print("'int_col' variable have {} unique category : \n{}\n".format(train_df['int_col'].nunique(), train_df['int_col'].unique()))
print('-'*125)

print("'accident' variable have {} unique category : \n{}\n".format(train_df['accident'].nunique(), train_df['accident'].unique()))
print('-'*125)

print("'clean_title' variable have {} unique category : \n{}\n".format(train_df['clean_title'].nunique(), train_df['clean_title'].unique()))
print('-'*125)

-----------------------------------------------------------------------------------------------------------------------------
Checking records for mis-spell, typo-error etc.
-----------------------------------------------------------------------------------------------------------------------------
'brand' variable have 53 unique category :
['Ford' 'BMW' 'Jaguar' 'Pontiac' 'Acura' 'Audi' 'GMC' 'Maserati'
 'Chevrolet' 'Porsche' 'Mercedes-Benz' 'Tesla' 'Lexus' 'Kia' 'Lincoln'
 'Dodge' 'Volkswagen' 'Land' 'Cadillac' 'Mazda' 'RAM' 'Subaru' 'Hyundai'
 'MINI' 'Jeep' 'Honda' 'Hummer' 'Nissan' 'Toyota' 'Volvo' 'Genesis'
 'Mitsubishi' 'Buick' 'INFINITI' 'McLaren' 'Scion' 'Lamborghini' 'Bentley'
 'Suzuki' 'Ferrari' 'Alfa' 'Rolls-Royce' 'Chrysler' 'Aston' 'Rivian'
 'Lotus' 'Saturn' 'Lucid' 'Mercury' 'Maybach' 'FIAT' 'Plymouth' 'Bugatti']

-----------------------------------------------------------------------------------------------------------------------------
'model' variable have 1827 unique category :
['F-150 Lariat' '335 i' 'XF Luxury' ... 'Q4 e-tron Sportback Premium'
 'Countryman Cooper' 'S-10 LS']

-----------------------------------------------------------------------------------------------------------------------------
'fuel_type' variable have 7 unique category :
['Gasoline' 'Hybrid' 'E85 Flex Fuel' 'Diesel' '–' 'Plug-In Hybrid'
 'not supported']

-----------------------------------------------------------------------------------------------------------------------------
'engine' variable have 1061 unique category :
['375.0HP 3.5L V6 Cylinder Engine Gasoline Fuel'
 '300.0HP 3.0L Straight 6 Cylinder Engine Gasoline Fuel'
 '300.0HP 4.2L 8 Cylinder Engine Gasoline Fuel' ... '3.0L'
 '3.0 Liter GTDI' '120.0HP 2.2L 4 Cylinder Engine Flex Fuel Capability']

-----------------------------------------------------------------------------------------------------------------------------
'transmission' variable have 46 unique category :
['10-Speed A/T' '6-Speed M/T' '6-Speed A/T'
 'Transmission w/Dual Shift Mode' 'A/T' '5-Speed M/T' '7-Speed A/T'
 '5-Speed A/T' '8-Speed A/T' 'Transmission Overdrive Switch'
 '9-Speed Automatic' '7-Speed M/T' '10-Speed Automatic'
 '6-Speed Automatic' 'M/T' '5-Speed Automatic' 'CVT Transmission'
 '9-Speed A/T' '8-Speed Automatic' '4-Speed A/T' 'Automatic' '1-Speed A/T'
 '8-Speed Automatic with Auto-Shift' '7-Speed DCT Automatic'
 'Automatic CVT' '7-Speed Automatic' '7-Speed Automatic with Auto-Shift'
 '4-Speed Automatic' '6-Speed Automatic with Auto-Shift' '6-Speed Manual'
 '7-Speed Manual' '6-Speed Electronically Controlled Automatic with O'
 '1-Speed Automatic' '10-Speed Automatic with Overdrive' '8-Speed Manual'
 '2-Speed A/T' 'CVT-F' '–' 'F' '9-Speed Automatic with Auto-Shift'
 '7-Speed' 'Variable' 'SCHEDULED FOR OR IN PRODUCTION' '6-Speed'
 '6 Speed At/Mt' '6 Speed Mt']

-----------------------------------------------------------------------------------------------------------------------------
'ext_col' variable have 260 unique category :
['Blue' 'Black' 'Purple' 'Gray' 'White' 'Red' 'Silver' 'Summit White'
 'Platinum Quartz Metallic' 'Green' 'Orange' 'Lunar Rock'
 'Red Quartz Tintcoat' 'Beige' 'Gold' 'Jet Black Mica'
 'Delmonico Red Pearlcoat' 'Brown' 'Rich Garnet Metallic'
 'Stellar Black Metallic' 'Yellow' 'Deep Black Pearl Effect' 'Metallic'
 'Ice Silver Metallic' 'Agate Black Metallic' 'Rosso Mars Metallic'
 'White Clearcoat' 'Santorini Black Metallic' 'DB Black Clearcoat'
 'Snowflake White Pearl' 'Glacial White Pearl' 'Maximum Steel Metallic'
 'Blue Caelum' 'Dark Matter Metallic' '–' 'Oxford White'
 'Cobra Beige Metallic' 'Velvet Red Pearlcoat' 'Python Green'
 'Obsidian Black Metallic' 'Beluga Black' 'Blue Reflex Mica'
 'Sparkling Silver' 'Black Clearcoat' 'Soul Red Crystal Metallic'
 'Bright White Clearcoat' 'Shimmering Silver' 'Midnight Black Metallic'
 'Cajun Red Tintcoat' 'Cirrus Silver Metallic' 'Blu'
 'Burnished Bronze Metallic' 'Hellayella Clearcoat' 'Diamond Black'
 'White Diamond Tri-Coat' 'Nebula Gray Pearl' 'Bronze Dune Metallic'
 'Polymetal Gray Metallic' 'Nightfall Gray Metallic' 'Fuji White'
 'Shadow Gray Metallic' 'Dark Moon Blue Metallic' 'Dark Sapphire'
 'Firecracker Red Clearcoat' 'Black Raven' 'White Knuckle Clearcoat'
 'Siren Red Tintcoat' 'Designo Magno Matte' 'Atomic Silver'
 'Billet Silver Metallic Clearcoat' 'Ember Pearlcoat' 'Magnetic Black'
 'Pacific Blue Metallic' 'Midnight Blue Metallic' 'Alta White'
 'Eiger Grey' 'Diamond White' 'Onyx' 'Hyper Red' 'Ebony Twilight Metallic'
 'Alpine White' 'Sonic Silver Metallic' 'Dark Ash Metallic'
 'Volcano Grey Metallic' 'Patriot Blue Pearlcoat' 'Onyx Black'
 'Titanium Silver' 'Granite Crystal Clearcoat Metallic' 'Nero Noctis'
 'Silver Zynith' 'Black Cherry' 'Iconic Silver Metallic' 'Nero Daytona'
 'Daytona Gray Pearl Effect' 'Dark Moss' 'Deep Crystal Blue Mica'
 'China Blue' 'Magnetic Metallic' 'Midnight Black' 'Vega Blue'
 'Sandstone Metallic' 'Machine Gray Metallic' 'C / C'
 'Platinum Gray Metallic' 'Silver Ice Metallic' 'Carrara White Metallic'
 'Black Sapphire Metallic' 'Go Mango!' 'White Frost Tri-Coat'
 'Lizard Green' 'Santorin Black' 'Twilight Black' 'Gecko Pearlcoat'
 'Satin Steel Metallic' 'Imperial Blue Metallic' 'Nautical Blue Pearl'
 'Stone Gray Metallic' 'Quartzite Grey Metallic' 'Majestic Black Pearl'
 'Shadow Black' 'Crimson Red Tintcoat' 'Silver Flare Metallic' 'Vik Black'
 'Lunar Silver Metallic' 'Maroon' 'Redline Red' 'Iridescent Pearl Tricoat'
 'Brilliant Silver Metallic' 'Lunar Blue Metallic' 'Matte White' 'Tan'
 'Stormy Sea' 'Twilight Blue Metallic' 'Ibis White'
 'Kodiak Brown Metallic' 'Crystal Black Silica' 'Sting Gray Clearcoat'
 'Pristine White' 'Pearl White' 'Antimatter Blue Metallic'
 'Tango Red Metallic' 'Crystal Black Pearl' 'Rift Metallic'
 'Glacier White Metallic' 'Quartz White' 'Black Obsidian'
 'Brilliant Black' 'Ruby Red Metallic Tinted Clearcoat'
 'Tungsten Metallic' 'Magnetite Black Metallic' 'Jupiter Red' 'Glacier'
 'Santorini Black' 'Navarre Blue'
 'Phantom Black Pearl Effect / Black Roof' 'Isle of Man Green Metallic'
 'Snowflake White Pearl Metallic' 'Brands Hatch Gray Metallic'
 'Volcanic Orange' 'Liquid Platinum' 'Bayside Blue'
 'Rapid Red Metallic Tinted Clearcoat' 'Majestic Plum Metallic'
 'White Platinum Tri-Coat Metallic' 'Mosaic Black Metallic' 'Chalk'
 'Black Noir Pearl' 'Nightfall Mica' 'Dark Gray Metallic'
 'Mythos Black Metallic' 'Blueprint' 'Quicksilver Metallic' 'Frozen White'
 'Lunare White Metallic' 'Verde' 'Dark Graphite Metallic' 'Mythos Black'
 'Ebony Black' 'Ultra Black' 'Ingot Silver Metallic'
 'Glacier Silver Metallic' 'Gun Metallic' 'Wind Chill Pearl'
 'Anodized Blue Metallic' 'designo Diamond White' 'Tempest' 'Caviar'
 'Phytonic Blue Metallic' 'Moonlight Cloud'
 'Daytona Gray Pearl Effect w/ Black Roof' 'Bianco Isis'
 'Carbonized Gray Metallic' 'Deep Blue Metallic' 'Ametrin Metallic'
 'Super Black' 'Rosso Corsa' 'Blue Metallic' 'Iridium Metallic'
 'Dark Slate Metallic' 'Manhattan Noir Metallic' 'Alfa White'
 'Baltic Gray' 'Northsky Blue Metallic' 'Super White'
 'Carbon Black Metallic' 'Horizon Blue' 'Jungle Green'
 'Cayenne Red Tintcoat' 'Pink' 'Daytona Gray' 'Gentian Blue Metallic'
 'Sangria Red' 'Kemora Gray Metallic' 'Magnetite Gray Metallic'
 'Octane Red Pearlcoat' 'Custom Color' 'Ultra White' 'Pacific Blue'
 'Ruby Flare Pearl' 'Caspian Blue' 'Silver Radiance'
 'Carpathian Grey Premium Metallic' 'Ice' 'Balloon White'
 'Shoreline Blue Pearl' 'Firenze Red Metallic' 'Remington Red Metallic'
 'Orca Black Metallic' 'Radiant Red Metallic II' 'Mineral White'
 'Glacier White' 'Snow White Pearl' 'Iridium Silver Metallic'
 'Carpathian Grey' 'Mountain Air Metallic' 'Selenite Gray Metallic'
 'Graphite Grey Metallic' 'Selenite Grey Metallic' 'Kinetic Blue'
 'Wolf Gray' 'Star White' 'Emin White' 'Indus Silver'
 'Matador Red Metallic' 'Portofino Gray' 'Black Forest Green'
 'Dazzling White' 'Flame Red Clearcoat' 'Glacier Blue Metallic'
 'Arctic White' 'Rosso' 'Silver Mist' 'Bianco Icarus Metallic'
 'Firenze Red' 'Ironman Silver' 'Red Obsession' 'Magnetic Gray Metallic'
 'Garnet Red Metallic' 'Vulcano Black Metallic' 'Magnetic Gray Clearcoat']

-----------------------------------------------------------------------------------------------------------------------------
'int_col' variable have 124 unique category :
['Gray' 'Black' 'Beige' 'Brown' 'Silver' 'Jet Black' 'Mesa' 'White' '–'
 'Red' 'Blue' 'Medium Stone' 'Ash' 'Ebony' 'Shara Beige' 'Tan'
 'Titan Black / Quarzit' 'Global Black' 'Orange' 'Saddle Brown' 'Nero Ade'
 'Beluga' 'Light Slate' 'Gold' 'Black Onyx' 'Nougat Brown' 'Camel'
 'Hotspur Hide' 'Charcoal' 'Satin Black' 'Deep Chestnut'
 'Diesel Gray / Black' 'White / Brown' 'AMG Black' 'Parchment' 'Shale'
 'Canberra Beige' 'Sahara Tan' 'Ebony / Pimento' 'Rhapsody Blue'
 'Medium Dark Slate' 'Rioja Red' 'Black / Express Red' 'Deep Garnet'
 'Portland' 'Sandstone' 'Dark Ash' 'Deep Cypress' 'Black / Stone Grey'
 'Chestnut' 'Navy Pier' 'Green' 'Giallo Taurus / Nero Ade'
 'Mistral Gray / Raven' 'Dark Gray' 'Amber' 'Charles Blue' 'Hotspur'
 'Medium Earth Gray' 'Ceramic' 'Kyalami Orange' 'Charcoal Black'
 'Adrenaline Red' 'Walnut' 'Brandy' 'Black / Saddle' 'Obsidian Black'
 'Oyster W/Contrast' 'Macchiato' 'Red / Black' 'Whisper Beige' 'Graphite'
 'Yellow' 'Medium Light Camel' 'Slate' 'Nero' 'Ebony Black' 'Espresso'
 'Cappuccino' 'Ivory / Ebony' 'Boulder' 'Medium Ash Gray' 'Platinum'
 'Light Platinum / Jet Black' 'Beluga Hide' 'Black / Graphite'
 'Canberra Beige/Black' 'Rock Gray' 'Dark Auburn' 'Almond Beige'
 'Sand Beige' 'Black / Brown' 'Ice' 'Silk Beige/Espresso Brown'
 'Dark Galvanized' 'Cobalt Blue' 'Grace White' 'Titan Black'
 'Cocoa / Dune' 'Light Gray' 'Camel Leather' 'Light Titanium'
 'Pimento Red w/Ebony' 'Sport' 'Oyster/Black' 'Black/Red'
 'Ebony / Ebony Accents' 'Cloud' 'Graystone' 'BLACK' 'Mountain Brown'
 'Linen' 'Caramel' 'Black / Gray' 'Blk' 'Black w/Red Stitching' 'Mocha'
 'Tupelo' 'Tan/Ebony' 'Parchment.' 'Black/Gun Metal' 'Very Light Cashmere'
 'Medium Pewter' 'Red/Black']

-----------------------------------------------------------------------------------------------------------------------------
'accident' variable have 2 unique category :
['None reported' 'At least 1 accident or damage reported']

-----------------------------------------------------------------------------------------------------------------------------
'clean_title' variable have 1 unique category :
['Yes']

-----------------------------------------------------------------------------------------------------------------------------

# 5) Data Cleaning & Preprocessing I
---